# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # build_app(scheme: "Jenkins")
    # upload_to_testflight
    gym(
    	scheme:"Jenkins",
    	export_method:"ad-hoc",
    	output_directory:"/Users/postop_iosdev/Desktop/iOS",
    	export_xcargs: "-allowProvisioningUpdates",
    	)
  end
end
